In [3]:
import numpy as np
import pandas as pd
import re

title_basics = pd.read_csv('~/greenfox/data-science/week-03/imdb/title.basics.tsv', sep='\t', low_memory=False)

In [66]:
import jupyternotify
ip = get_ipython()
ip.register_magics(jupyternotify.JupyterNotifyMagics)

In [4]:
title_basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,\N,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"

In [5]:
cols = ['runtimeMinutes', 'startYear', 'endYear', 'isAdult']

In [6]:
title_basics[cols] = title_basics[cols].replace('\\N', np.nan)

In [7]:
title_basics.drop(title_basics.loc[title_basics.runtimeMinutes.str.isnumeric() == False].index, inplace=True)

In [8]:
title_basics.runtimeMinutes = title_basics.runtimeMinutes.astype(float)

In [9]:
title_basics.drop(title_basics.loc[(title_basics['isAdult'] != 0) & (title_basics['isAdult'] != 1)].index, inplace=True)

In [10]:
title_basics.tconst.is_unique

True

In [11]:
regex = re.compile(r'^tt\d{7}')

In [12]:
title_basics.tconst.str.match(regex).all()

True

In [13]:
title_basics.titleType.unique()

array(['short', 'movie', 'tvMovie', 'tvSeries', 'tvEpisode', 'tvShort',
       'tvMiniSeries', 'tvSpecial', 'video', 'videoGame'], dtype=object)

In [14]:
title_basics.drop(columns='originalTitle', inplace=True)

In [15]:
title_basics.head()

,tconst,titleType,primaryTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,0,1894,NaN,1.0,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,0,1892,NaN,5.0,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,0,1892,NaN,4.0,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,0,1892,NaN,NaN,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,0,1893,NaN,1.0,"Comedy,Short"

In [16]:
title_basics.startYear.describe()

count     5263192
unique        145
top          2017
freq       304998
Name: startYear, dtype: object

In [17]:
max = title_basics.loc[:, 'startYear'].dropna().max()

In [18]:
max

'2115'

In [19]:
min = title_basics.loc[:, 'startYear'].dropna().min()

In [20]:
min

'1874'

In [21]:
title_basics.loc[title_basics['startYear'] == '2115']

,tconst,titleType,primaryTitle,isAdult,startYear,endYear,runtimeMinutes,genres
3504889,tt5174640,movie,100 Years,0,2115,NaN,NaN,Drama

In [22]:
title_basics.drop(title_basics[title_basics['startYear'] > '2019'].index, inplace=True)

In [23]:
title_basics.endYear.unique()

array([nan, '1947', '1950', '1949', '1958', '1951', '1952', '1954',
       '1957', '1953', '1956', '1967', '1971', '1959', '1955', '1963',
       '1960', '1961', '1965', '1980', '2016', '1986', '1962', '1972',
       '1966', '1970', '2009', '1987', '1991', '1974', '1992', '1976',
       '1975', '1982', '2010', '1984', '1964', '1968', '1989', '1994',
       '1973', '1969', '2004', '1981', '1977', '1999', '1988', '2003',
       '1978', '2001', '2013', '1993', '1997', '1996', '2011', '2005',
       '1995', '1979', '2006', '1985', '1983', '1998', '1990', '2008',
       '2007', '2015', '2014', '2000', '2018', '2002', '2012', '2019',
       '1948', '2017', '1938', '1942', '1933', '1946', '1945', '2020',
       '1941', '1937', '1939', '1932', '2025', '1936', '1924', '1927',
       '1935', '2024', '2027', '2021', '2022'], dtype=object)

In [60]:
title_basics[title_basics['endYear'].isnull()].shape

(5526293, 8)

In [59]:
title_basics.loc[(title_basics['runtimeMinutes'] > 300) & (title_basics['titleType'] != 'tvSeries')].shape

(2215, 8)

In [75]:
%%notify
import time
time.sleep(5)

In [87]:
%%notify

def extr_categories(row):
    cats = row.genres.split(',')
    for cat in cats:
        if cat not in categories:
            categories.append(cat)                            
    return row

categories = []
title_basics.apply(extr_categories, axis='columns')

,tconst,titleType,primaryTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,0,1894,NaN,1.0,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,0,1892,NaN,5.0,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,0,1892,NaN,4.0,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,0,1892,NaN,NaN,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,0,1893,NaN,1.0,"Comedy,Short"
5,tt0000006,short,Chinese Opium Den,0,1894,NaN,1.0,Short
6,tt0000007,short,Corbett and Courtney Before the Kinetograph,0,1894,NaN,1.0,"Short,Sport"
7,tt0000008,short,Edison Kinetoscopic Record of a Sneeze,0,1894,NaN,1.0,"Documentary,Short"
8,tt0000009,movie,Miss Jerry,0,1894,NaN,45.0,Romance
9,tt0000010,short,Exiting the Factory,0,1895,NaN,1.0,"Documentary,Short"
10,tt0000011,short,Akrobatisches Potpourri,0,1895,NaN,1.0,"Documentary,Short"
11,tt0000012,short,The Arrival of a Train,0,1896,NaN,1.0,"Documentary,Short"
12,tt0000013,short,The Photographical Congress Arrives in Lyon,0,1895,NaN,1.0,"Documentary,Short"
13,tt0000014,short,The Sprinkler Sprinkled,0,1895,NaN,1.0,"Comedy,Short"
14,tt0000015,short,Autour d'une cabine,0,1894,NaN,2.0,"Animation,Short"
15,tt0000016,short,Barque sortant du port,0,1895,NaN,1.0,"Documentary,Short"
16,tt0000017,short,Italienischer Bauerntanz,0,1895,NaN,1.0,"Documentary,Short"
17,tt0000018,short,Das boxende Känguruh,0,1895,NaN,1.0,Short
18,tt0000019,short,The Clown Barber,0,1898,NaN,NaN,"Comedy,Short"
19,tt0000020,short,The Derby 1895,0,1895,NaN,1.0,"Documentary,Short,Sport"
20,tt0000022,short,Blacksmith Scene,0,1895,NaN,1.0,"Documentary,Short"
21,tt0000023,short,The Sea,0,1895,NaN,1.0,"Documentary,Short"
22,tt0000024,short,Opening of the Kiel Canal,0,1895,NaN,NaN,"News,Short"
23,tt0000025,short,The Oxford and Cambridge University Boat Race,0,1895,NaN,NaN,"News,Short,Sport"
24,tt0000026,short,The Messers. Lumière at Cards,0,1896,NaN,1.0,"Documentary,Short"
25,tt0000027,short,Cordeliers' Square in Lyon,0,1895,NaN,1.0,"Documentary,Short"
26,tt0000028,short,Fishing for Goldfish,0,1895,NaN,1.0,"Documentary,Short"
27,tt0000029,short,Baby's Dinner,0,1895,NaN,1.0,"Documentary,Short"
28,tt0000030,short,Rough Sea at Dover,0,1895,NaN,1.0,"Documentary,Short"
29,tt0000031,short,Jumping the Blanket,0,1895,NaN,1.0,"Documentary,Short"
...,...,...,...,...,...,...,...,...
5573054,tt9636426,tvEpisode,17 January 2019: Lunchtime Bulletin,0,2019,NaN,4.0,News
5573055,tt9636428,tvEpisode,I Think It Played Before Only,0,NaN,NaN,NaN,\N
5573056,tt9636430,tvEpisode,17 January 2019: Evening Bulletin,0,2019,NaN,30.0,News
5573057,tt9636432,short,Greta Follows Rivers,0,2018,NaN,NaN,"Drama,Short"
5573058,tt9636436,tvEpisode,Episode #5.121,0,1953,NaN,NaN,Music
5573059,tt9636438,tvEpisode,Episode #5.122,0,1953,NaN,NaN,Music
5573060,tt9636440,tvEpisode,Tattling,0,2019,NaN,NaN,Reality-TV
5573061,tt9636442,short,Media War in El Salvador,0,1989,NaN,24.0,"Documentary,Short"
5573062,tt9636444,tvEpisode,Episode #5.123,0,1953,NaN,NaN,Music
5573063,tt9636446,tvEpisode,Hau' ma's z'samm - Jugend und Gewalt,0,1988,NaN,NaN,Talk-Show
5573064,tt9636448,tvEpisode,No Longer a Virgin,0,2019,NaN,NaN,Reality-TV
5573065,tt9636450,tvEpisode,Episode #5.124,0,1953,NaN,NaN,Music
5573066,tt9636452,tvEpisode,The 2019 Golden Globe Awards,0,2019,NaN,NaN,News
5573067,tt9636456,tvEpisode,Episode #5.125,0,1953,NaN,NaN,Music
5573068,tt9636464,tvEpisode,Episode #5.126,0,1953,NaN,NaN,Music
5573069,tt9636466,tvEpisode,Episode #5.127,0,1953,NaN,NaN,Music
5573070,tt9636468,tvEpisode,Episode #5.128,0,1953,NaN,NaN,Music
5573071,tt9636470,tvEpisode,Episode dated 17 January 2019,0,2019,NaN,NaN,News
5573072,tt9636472,tvEpisode,Episode dated 17 January 2019,0,2019,NaN,NaN,News
5573073,tt9636474,tvEpisode,Episode #5.129,0,1953,NaN,NaN,Music
5573074,tt9636476,tvEpisode,Tortoise First Date,0,2019,NaN,NaN,Documentary
5573075,tt9636480,tvMiniSeries,Guomin Laogong Dai Huijia,0,2016,NaN,11.0,Romance
5573076,tt9636482,tvEpisode,Episode dated 17 January 2019,0,2019,NaN,NaN,News
5573077,tt9636484,tvEpisode,Episode #5.130,0,1953,NaN,NaN,Music
5573078,tt9636486,tvEpisode,Episode #5.131,0,1953,NaN,NaN,Music
5573079,tt9636492,tvEpisode,Episode #6.1,0,1953,NaN,NaN,Music
5573080,tt9636500,movie,Good Boys,0,2019,NaN,NaN,Drama
5573081,tt9636502,tvEpisode,Decades Summarized - The 1910s,0,2019,NaN,5.0,"History,Short"
5573082,tt9636506,tvEpisode,Episode dated 17 January 2019,0,2019,NaN,NaN,Talk-Show
5573083,tt9636512,video,Jeremiah Watkins and the Green Beret Heckler,0,2019,NaN,NaN,"Comedy,Short"

In [88]:
categories

['Documentary',
 'Short',
 'Animation',
 'Comedy',
 'Romance',
 'Sport',
 'News',
 'Drama',
 'Fantasy',
 'Horror',
 'Biography',
 'Music',
 'War',
 'Crime',
 'Western',
 'Family',
 'Adventure',
 'History',
 'Sci-Fi',
 'Action',
 'Mystery',
 '\\N',
 'Thriller',
 'Musical',
 'Film-Noir',
 'Game-Show',
 'Talk-Show',
 'Reality-TV',
 'Adult']

In [89]:
title_basics['genres'] = title_basics['genres'].replace('\\N', '')

In [90]:
title_basics.loc[title_basics['genres'] == '\\N']

Empty DataFrame
Columns: [tconst, titleType, primaryTitle, isAdult, startYear, endYear, runtimeMinutes, genres]
Index: []